version: '2.1'
orbs:
  node: circleci/node@4.5.2
  gh: circleci/github-cli@1.0.3
workflows:
  test-and-release:
    jobs:
      - node/test
      - gh/release:
          notes-file: changelog.md
          tag: 1.1.0
          title: "Add Feature: Blinking text"
          requires:
            - node/test
          context:
            - GITHUB_CREDS
